** `bald_aufstufen.py`

To use the TUI visualization script, follow these steps:

*** Install the following dependencies:
- Python 3
- the `make` utility (optional)

*** Setup the virtual environment for Python.
If you have the `make` utility installed, run
#+begin_src shell
    make setup
#+end_src
Otherwise:
#+begin_src shell
    cd bin && ./setup.sh
#+end_src
This will create a virtual environment for Python, and 
install the dependencies listed in `requirements.txt`.

*** Download the NaMi export files.
In the (near?) future, this will likely be done automatically using 
the `pynami` Python package. For now though, download the file 
`Mitglieder Grundinformationen mit Tätigkeiten und Stufe Abteilung.xlsx` 
from NaMi. Make sure that the downloaded file has exactly this name, 
you probably will have to rename it.

*** Move the file into the `/data/in/` directory.
Here, `/` labels the repository root directory.

*** Run the visualization script.
If you have the `make` utility installed, run
#+begin_src shell
    make 
#+end_src
Otherwise:
#+begin_src shell
    cd bin && ./run.sh
#+end_src
